// scenarios.js — 100 scénarios officiels (numéros 01-99 + 00)
// Source : Délégation à la Sécurité Routière / DSR-BRPCE (jan. 2018)
// Chaque scénario = les 2 derniers chiffres du compteur kilométrique du véhicule d'examen.

const SCENARIOS = [
  {
    id: "01",
    type1: "VI",
    q1: "Montrez la commande de réglage de hauteur des feux.",
    a1: "Dispositif situé en général à gauche du volant.",
    explain1: "Ce correcteur de site permet d'adapter l'angle des feux selon la charge du véhicule. Plus la voiture est chargée à l'arrière, plus les feux pointent vers le haut et risquent d'éblouir.",
    photo1: "correcteur-feux.jpg",
    q2: "Pourquoi doit-on régler la hauteur des feux ?",
    a2: "Pour ne pas éblouir les autres usagers.",
    explain2: "Un mauvais réglage peut réduire la visibilité des conducteurs en face et provoquer des accidents. C'est aussi un point de contrôle technique.",
    q3: "Comment et pourquoi protéger une zone de danger en cas d'accident de la route ?",
    a3: "En délimitant clairement et largement la zone de danger de façon visible pour protéger les victimes et éviter un sur-accident.",
    explain3: "Le sur-accident (un 2e accident lié au premier) est fréquent et mortel. Baliser large et tôt est la priorité absolue avant même les premiers secours."
  },
  {
    id: "02",
    type1: "VE",
    q1: "Montrez où s'effectue le remplissage du produit lave-glace.",
    a1: "Ouvrir le capot et montrer le bocal lave-glace (bouchon bleu généralement).",
    explain1: "Le bocal lave-glace est distinct du liquide de refroidissement. Ne jamais les confondre — mettre de l'eau dans le refroidissement ou du lave-glace dans le mauvais réservoir peut endommager le moteur.",
    photo1: "bocal-lave-glace.jpg",
    q2: "Pourquoi est-il préférable d'utiliser un liquide lave-glace spécial en hiver ?",
    a2: "Pour éviter le gel du liquide.",
    explain2: "Un liquide gelé dans le circuit peut bloquer les gicleurs, voire faire éclater le bocal. En hiver, utiliser un liquide antigel conçu pour résister à -20°C ou moins.",
    q3: "Quels comportements adopter en cas de diffusion du signal d'alerte du Système d'Alerte et d'Information des Populations (SAIP) ?",
    a3: "Se mettre en sécurité. S'informer via les médias et sites internet des autorités. Respecter les consignes des autorités.",
    explain3: "Le SAIP remplace l'ancien réseau de sirènes. Son signal = danger imminent (catastrophe, attentat…). L'application SAIP sur smartphone permet aussi de recevoir ces alertes."
  },
  {
    id: "03",
    type1: "VI",
    q1: "Mettez le rétroviseur intérieur en position « nuit ».",
    a1: "Basculer la languette sous le rétroviseur (ou indiquer le système automatique s'il est équipé).",
    explain1: "La position nuit incline légèrement le miroir pour renvoyer les phares des voitures derrière vers le bas. Sans ça, les feux du suiveur créent un éblouissement direct dans les yeux du conducteur.",
    photo1: "retroviseur-nuit.jpg",
    q2: "Quel est l'intérêt de la position nuit ?",
    a2: "Ne pas être ébloui par les feux du véhicule suiveur.",
    explain2: "L'éblouissement provoque une cécité temporaire de 2 à 5 secondes. À 90 km/h, c'est 125 mètres parcouru 'à l'aveugle'.",
    q3: "Comment est composé le signal d'alerte du SAIP diffusé par les sirènes ?",
    a3: "Deux codes : le Signal National d'Alerte (SNA) = variation du signal sur 3 cycles successifs. Le signal de fin d'alerte = signal continu.",
    explain3: "La modulation (montée et descente du son) = danger en cours. Le signal continu = fin d'alerte. Un signal de sirène monotone dans la rue signifie donc que c'est terminé."
  },
  {
    id: "04",
    type1: "VE",
    q1: "Contrôlez l'état du flanc sur l'un des pneumatiques.",
    a1: "Vérification visuelle du flanc : en bon état, sans coupure, boursouflure ni déformation. Toute anomalie doit être signalée.",
    explain1: "Le flanc est la partie latérale du pneu, la plus vulnérable aux chocs de trottoir. Une boursouflure (hernie) = risque d'éclatement imminent, même à faible vitesse.",
    photo1: "flanc-pneumatique.jpg",
    q2: "Citez un endroit où l'on peut trouver les pressions préconisées pour les pneumatiques.",
    a2: "Sur une plaque sur une portière (côté conducteur), dans la notice d'utilisation du véhicule, ou au niveau de la trappe à carburant.",
    explain2: "La pression est différente avant/arrière et selon la charge. Sur route, une pression insuffisante = surchauffe du pneu, usure anormale et consommation accrue. Vérifier à froid (moteur arrêté depuis 2h).",
    q3: "Sur autoroute, comment indiquer avec précision les lieux d'un accident depuis un téléphone portable ?",
    a3: "En indiquant le numéro de l'autoroute, le sens de circulation et le point kilométrique.",
    explain3: "Les bornes d'appel d'urgence orange situées tous les 2 km sur les autoroutes transmettent automatiquement votre position — idéales si vous êtes à pied après une panne."
  },
  {
    id: "05",
    type1: "VI",
    q1: "Faites fonctionner les essuie-glaces avants du véhicule sur la position la plus rapide.",
    a1: "Actionner le levier des essuie-glaces (sur la colonne de direction) et le placer sur la position la plus rapide (vitesse max).",
    explain1: "Les positions vont généralement d'intermittent (INT) à 1, 2, puis rapide. En fortes pluies, la position la plus rapide est indispensable pour maintenir la visibilité.",
    photo1: "levier-essuie-glaces.jpg",
    q2: "Comment détecter l'usure des essuie-glaces en circulation ?",
    a2: "En cas de pluie, lorsqu'ils laissent des traces sur le pare-brise.",
    explain2: "Des stries, traînées ou zones non essuyées indiquent que le caoutchouc est durci ou abîmé. À changer avant l'hiver (tous les 1-2 ans en général).",
    q3: "Comment vérifier la respiration d'une victime ?",
    a3: "Regarder si le ventre et la poitrine se soulèvent, et sentir de l'air à l'expiration.",
    explain3: "Technique LVA (Voir, Écouter, Sentir) : se pencher sur la victime, joue près de sa bouche, et observer la poitrine pendant 10 secondes. Si pas de respiration → commencer la RCP."
  },
  {
    id: "06",
    type1: "VE",
    q1: "Vérifiez l'état et la propreté des plaques d'immatriculation.",
    a1: "Vérification des plaques avant et arrière : propres, lisibles et en bon état. Toute anomalie doit être signalée.",
    explain1: "Une plaque illisible (sale, tordue, partiellement masquée) constitue une infraction. Elle doit être visible de nuit grâce à l'éclairage de plaque arrière.",
    photo1: "plaque-immatriculation.jpg",
    q2: "Quelles sont les précautions à prendre en cas d'installation d'un porte-vélo ?",
    a2: "La plaque d'immatriculation et les feux doivent rester visibles.",
    explain2: "Un porte-vélo qui masque la plaque ou les feux est illégal. Il faut alors fixer une plaque et des feux déportés sur le porte-vélo lui-même.",
    q3: "Qu'est-ce qu'une perte de connaissance ?",
    a3: "C'est lorsque la victime ne répond pas et ne réagit pas, mais respire.",
    explain3: "Différence clé : perte de connaissance (respire) → PLS. Arrêt cardiaque (ne respire pas) → RCP. Confondre les deux peut être fatal."
  },
  {
    id: "07",
    type1: "VI",
    q1: "Vérifiez la présence du gilet de haute visibilité.",
    a1: "Indiquer où se trouve le gilet dans le véhicule, sans obligation de le sortir.",
    explain1: "Le gilet doit être accessible de l'intérieur du véhicule (pas dans le coffre) pour pouvoir le mettre AVANT de sortir en cas de panne.",
    photo1: "gilet-haute-visibilite.jpg",
    q2: "En cas de panne ou d'accident, quel autre accessoire de sécurité est obligatoire ?",
    a2: "Le triangle de pré-signalisation.",
    explain2: "Ces deux équipements sont obligatoires depuis 2008. L'amende pour absence : 135€. Sur autoroute, le triangle ne doit PAS être utilisé (trop dangereux d'aller le placer).",
    q3: "Si un dégagement d'urgence de la victime est nécessaire, où doit-elle être déplacée ?",
    a3: "Dans un endroit suffisamment éloigné du danger et de ses conséquences.",
    explain3: "Le dégagement d'urgence ne doit se faire QUE si la victime est en danger immédiat (incendie, explosion imminente, noyade). Déplacer une victime sans raison peut aggraver une blessure cervicale."
  },
  {
    id: "08",
    type1: "VE",
    q1: "Montrez où s'effectue le contrôle du niveau du liquide de frein.",
    a1: "Ouvrir le capot et montrer le bocal de liquide de frein (petit réservoir transparent avec repères MIN/MAX, généralement près du maître-cylindre).",
    explain1: "Le liquide de frein est hygroscopique (absorbe l'humidité). Un niveau trop bas indique soit une fuite, soit une usure des plaquettes. À ne jamais négliger — le freinage peut devenir défaillant.",
    photo1: "bocal-liquide-frein.jpg",
    q2: "Quelle est la conséquence d'un niveau insuffisant du liquide de frein ?",
    a2: "Une perte d'efficacité du freinage.",
    explain2: "Si le niveau est bas à cause d'une fuite, un choc hydraulique peut vider le circuit en quelques freinages. La pédale 'tombe dans le plancher' = freinage quasi nul.",
    q3: "En cas de panne ou d'accident, quel équipement de sécurité doit être porté avant de quitter le véhicule ?",
    a3: "Le gilet de haute visibilité.",
    explain3: "Statistique : la majorité des piétons tués sur route la nuit l'étaient à cause d'un manque de visibilité. Le gilet jaune multiplie la distance de détection par 3 à 4."
  },
  {
    id: "09",
    type1: "VI",
    q1: "Vérifiez la présence du certificat d'immatriculation du véhicule (ou carte grise).",
    a1: "Montrer le certificat d'immatriculation (la photocopie est acceptée).",
    explain1: "Depuis 2017, le certificat d'immatriculation peut être présenté en version numérique (via l'app ANTS). La photocopie est acceptée depuis 2013.",
    photo1: "carte-grise.jpg",
    q2: "Quels sont les deux autres documents obligatoires à présenter en cas de contrôle par les forces de l'ordre ?",
    a2: "L'attestation d'assurance et le permis de conduire.",
    explain2: "3 documents obligatoires : permis de conduire + carte grise + attestation assurance. Sans assurance = 3 750€ d'amende + suspension de permis possible.",
    q3: "Pourquoi l'alerte auprès des services de secours doit-elle être rapide et précise ?",
    a3: "Pour permettre aux services de secours d'apporter les moyens adaptés aux victimes dans le délai le plus court.",
    explain3: "Le délai d'intervention est crucial : pour un arrêt cardiaque, chaque minute sans défibrillation réduit les chances de survie de 10%. Être précis (lieu, nature, nombre de victimes) détermine les moyens envoyés."
  },
  {
    id: "10",
    type1: "VE",
    q1: "Contrôlez l'état de tous les balais d'essuie-glace du véhicule.",
    a1: "Inspecter visuellement les balais : en bon état, sans craquelure ni déformation du caoutchouc.",
    explain1: "Soulever le bras et faire glisser le caoutchouc entre les doigts pour détecter les irrégularités. Un balai usé laisse des bandes non essuyées = visibilité dangereusement réduite.",
    photo1: "balais-essuie-glace.jpg",
    q2: "Quel est le risque de circuler avec des balais d'essuie-glace défectueux ?",
    a2: "Une mauvaise visibilité en cas d'intempéries.",
    explain2: "Par pluie forte, des balais défectueux peuvent réduire la visibilité à quelques mètres. Le contrôle technique pénalise les balais en mauvais état.",
    q3: "Quels sont les numéros d'urgence à composer ?",
    a3: "18 (pompiers), 15 (SAMU), 112 (numéro d'urgence européen valable dans toute l'UE).",
    explain3: "Le 112 fonctionne même sans crédit, sans code PIN, et depuis n'importe quel réseau mobile en Europe. À retenir absolument. Le 17 (police) et 115 (SDF) sont aussi des numéros d'urgence."
  },
  {
    id: "11",
    type1: "VI",
    q1: "Montrez l'indicateur de niveau de carburant.",
    a1: "Montrer la jauge de carburant sur le tableau de bord (aiguille entre E et F, ou affichage numérique).",
    explain1: "La jauge indique le niveau de carburant restant. La flèche à côté du symbole pompe indique de quel côté est le bouchon du réservoir — utile à la station !",
    photo1: "jauge-carburant.jpg",
    q2: "Quelles sont les précautions à prendre lors du remplissage du réservoir ?",
    a2: "Arrêter le moteur, ne pas fumer, ne pas téléphoner.",
    explain2: "Les vapeurs d'essence sont très inflammables. Une étincelle (téléphone, allumette, décharge statique) peut déclencher un incendie. Le moteur doit être coupé pour éviter l'aspiration des vapeurs.",
    q3: "Quels comportements adopter en présence d'une victime qui ne répond pas et ne réagit pas, mais respire ?",
    a3: "La placer en Position Latérale de Sécurité (PLS), alerter les secours, surveiller la respiration jusqu'à leur arrivée.",
    explain3: "La PLS évite que la victime s'étouffe avec sa langue ou ses vomissements. La face vers le bas légèrement, bouche légèrement ouverte vers le sol."
  },
  {
    id: "12",
    type1: "VE",
    q1: "Montrez où s'effectue le remplissage du liquide de refroidissement.",
    a1: "Ouvrir le capot et montrer le bocal de liquide de refroidissement (généralement transparent avec repères MIN/MAX).",
    explain1: "Ne jamais ouvrir ce bocal quand le moteur est chaud — la pression projetterait du liquide bouillant. Attendre que le moteur soit complètement froid.",
    photo1: "bocal-refroidissement.jpg",
    q2: "Quel est le danger si l'on complète le niveau du liquide lorsque le moteur est chaud ?",
    a2: "Un risque de brûlure.",
    explain2: "Le liquide est à plus de 90°C sous pression. L'ouverture du bouchon provoque une décompression violente — projection de liquide bouillant sur le visage et les mains.",
    q3: "Comment arrêter une hémorragie ?",
    a3: "En appuyant fortement sur l'endroit qui saigne avec les doigts ou la paume de la main, en mettant un tissu propre sur la plaie.",
    explain3: "La compression directe est le seul geste efficace immédiatement. Maintenir la pression sans relâcher jusqu'à l'arrivée des secours. Ne pas retirer le tissu s'il se gorge de sang — en ajouter un par-dessus."
  },
  {
    id: "13",
    type1: "VI",
    q1: "Actionnez le dégivrage de la lunette arrière et montrez le voyant ou le repère correspondant.",
    a1: "Appuyer sur le bouton de dégivrage de lunette arrière (symbole = rectangle avec lignes horizontales et flèches) et montrer le voyant qui s'allume.",
    explain1: "Le dégivrage chauffe des filaments conducteurs intégrés dans la vitre. Bien vérifier que la lunette est entièrement dégagée avant de prendre la route — la visibilité arrière est obligatoire.",
    photo1: "degivrage-lunette.jpg",
    q2: "Quelle peut être la conséquence d'une panne de dégivrage de la lunette arrière ?",
    a2: "Une insuffisance ou une absence de visibilité vers l'arrière.",
    explain2: "En hiver, sans dégivrage, la lunette reste givrée et le conducteur ne peut pas utiliser le rétroviseur intérieur. Cela augmente drastiquement les risques lors des manœuvres et changements de voie.",
    q3: "Hors autoroute, en cas de panne ou d'accident, où doit être placé le triangle de pré-signalisation ?",
    a3: "À environ 30 m de la panne ou de l'accident, ou avant un virage, ou avant un sommet de côte.",
    explain3: "Sur autoroute, ne JAMAIS placer le triangle (trop dangereux). Sur route classique, 30 m = environ 10 grandes enjambées. Toujours porter le gilet avant de sortir."
  },
  {
    id: "14",
    type1: "VE",
    q1: "Contrôlez l'état, la propreté et le fonctionnement de tous les clignotants côté trottoir.",
    a1: "Vérification des clignotants avant, latéral et arrière côté trottoir : propres, en bon état et qui fonctionnent. Toute anomalie doit être signalée.",
    explain1: "Pour vérifier seul : activer les clignotants et faire le tour du véhicule. Ou observer le reflet dans une vitrine. Côté trottoir = le côté passager lors d'un stationnement normal.",
    photo1: "clignotants-trottoir.jpg",
    q2: "Quelle est la signification d'un clignotement plus rapide que d'habitude ?",
    a2: "Non-fonctionnement de l'une des ampoules.",
    explain2: "Le système de clignotement accélère pour alerter le conducteur qu'une ampoule est grillée. C'est un système de sécurité intégré — à corriger rapidement car les autres usagers ne verront plus vos intentions.",
    q3: "Quelles sont les conditions pour réaliser le dégagement d'urgence d'une victime ?",
    a3: "La victime doit être visible, facile à atteindre, rien ne doit gêner son dégagement, et il faut être sûr de pouvoir le réaliser.",
    explain3: "Le dégagement d'urgence n'est justifié que si le danger est RÉEL, IMMÉDIAT et NON CONTRÔLABLE. Exemple : véhicule en feu. Sinon, ne pas bouger la victime — une lésion cervicale peut être aggravée."
  },
  {
    id: "15",
    type1: "VI",
    q1: "Montrez le voyant d'alerte signalant une pression insuffisante d'huile dans le moteur.",
    a1: "Montrer le voyant en forme de lampe à huile (icône rouge) sur le tableau de bord.",
    explain1: "Ce voyant rouge est critique : il ne s'allume que si la pression est déjà très basse. Arrêter immédiatement le moteur si ce voyant s'allume en circulation — continuer = destruction du moteur en quelques minutes.",
    photo1: "voyant-huile.jpg",
    q2: "Quelles sont les conditions à respecter pour contrôler le niveau d'huile ?",
    a2: "Moteur froid et sur un terrain plat.",
    explain2: "Un moteur chaud fausse la lecture car l'huile est dilatée et encore dans les conduits. Sur terrain en pente, l'huile se répartit inégalement dans le carter, donnant un niveau faux à la jauge.",
    q3: "Quelles sont les trois informations à transmettre aux services de secours ?",
    a3: "Le numéro de téléphone depuis lequel l'appel est émis, la nature du problème, et la localisation la plus précise possible.",
    explain3: "Mémo : QUI appelle (numéro), QUOI (nature), OÙ (localisation). Ces 3 infos permettent aux secours d'envoyer les bons moyens au bon endroit sans rappeler."
  },
